name: Docker Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - 'main'
      - 'master'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { platform: 'linux/amd64', tag: 'latest', dockerfile: 'Dockerfile' }
          - { platform: 'linux/arm64', tag: 'latest-arm', dockerfile: 'Dockerfile.arm' }
          - { platform: 'linux/arm/v7', tag: 'latest-armv7', dockerfile: 'Dockerfile.armv7' }
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.config.dockerfile }}
          platforms: ${{ matrix.config.platform }}
          push: true
          tags: smolgrrr/libreddit:${{ matrix.config.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  create-multiarch-manifest:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push multiarch manifest
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag smolgrrr/libreddit:latest --push .
      
